# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.4.dev17+ged07fb1.d20230316'
__version_tuple__ = version_tuple = (0, 2, 4, 'dev17', 'ged07fb1.d20230316')
