name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
        if: always()
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: always()
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Tox Test ${{ matrix.os }} ${{ matrix.python-version }}
        if: always()
        run: tox